python run_speech_recognition_ctc.py \
	--dataset_name="mozilla-foundation/common_voice_13_0" \
	--model_name_or_path="facebook/wav2vec2-large-xlsr-53" \
	--dataset_config_name="de" \
	--output_dir="./wav2vec2-large-xlsr-53-german-cv13" \
	--overwrite_output_dir \
	--num_train_epochs="15" \
	--per_device_train_batch_size="64" \
	--gradient_accumulation_steps="2" \
	--learning_rate="3e-4" \
	--warmup_steps="500" \
	--evaluation_strategy="steps" \
	--text_column_name="sentence" \
	--length_column_name="input_length" \
	--save_steps="400" \
	--eval_steps="100" \
	--layerdrop="0.0" \
	--save_total_limit="3" \
	--freeze_feature_encoder \
	--gradient_checkpointing \
	--chars_to_ignore \; \: \" “ % ‘ ” � \
	--fp16 \
	--group_by_length \
	--push_to_hub \
	--do_train --do_eval \
    --preprocessing_num_workers="8"